-- EXP-3--DML
CREATE DATABASE STUDENTSDB;
USE STUDENTSDB;

CREATE TABLE STUDENTS(
	STU_ID INT PRIMARY KEY AUTO_INCREMENT,
    STU_NAME VARCHAR(20) NOT NULL,
    STU_AGE INT CHECK(STU_AGE>18),
    STU_ADDRESS VARCHAR(20) DEFAULT "PUNE",
    STU_GMAIL VARCHAR(20) UNIQUE
    );

ALTER TABLE STUDENTS 
MODIFY STU_NAME VARCHAR(40);


INSERT INTO STUDENTS(STU_NAME,STU_AGE,STU_ADDRESS,STU_GMAIL) VALUES
("ROHAN PATIL",21,"JALNA","ROHAN@GMAIL.COM"),
("PRAFULL",19,"PUNE","P@GMAIL.COM");

SELECT * FROM STUDENTS;

UPDATE STUDENTS 
SET STU_NAME="PRATHMESH" WHERE STU_ID=1;

