-- EXP-2:-- INTEGRITY CONSTRAINTS
CREATE DATABASE STUDENTSDB;
USE STUDENTSDB;

CREATE TABLE STUDENTS(
	STU_ID INT PRIMARY KEY AUTO_INCREMENT,
    STU_NAME VARCHAR(20) NOT NULL,
    STU_AGE INT CHECK(STU_AGE>18),
    STU_ADDRESS VARCHAR(20) DEFAULT "PUNE",
    STU_GMAIL VARCHAR(20) UNIQUE
    );
    
INSERT INTO STUDENTS(STU_NAME,STU_AGE,STU_ADDRESS,STU_GMAIL) VALUES
("ROHAN PATIL",21,"JALNA","ROHAN@GMAIL.COM"),
("PRAFULL",19,"PUNE","P@GMAIL.COM");

CREATE TABLE DEPARTMENT(
	DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPT_NAME VARCHAR(20),
    STU_ID INT 
    );
 
ALTER TABLE DEPARTMENT
ADD CONSTRAINT FOREIGN KEY(STU_ID) REFERENCES STUDENTS(STU_ID);

INSERT INTO DEPARTMENT(DEPT_NAME,STU_ID) VALUES
("AI",2),
("CSE",1);

SELECT * FROM DEPARTMENT;