CREATE DATABASE STUDENTSDB;
USE STUDENTSDB;

CREATE TABLE STUDENTS(
	STU_ID INT PRIMARY KEY AUTO_INCREMENT,
    STU_NAME VARCHAR(20) NOT NULL,
    STU_AGE INT CHECK(STU_AGE>18),
    STU_MARKS INT NOT NULL
    );
    
ALTER TABLE STUDENTS 
ADD COLUMN STU_ADDRESS VARCHAR(20);

INSERT INTO STUDENTS(STU_NAME,STU_AGE,STU_ADDRESS,STU_MARKS) VALUES
("OM",22,"MUMBAI",90),
("DHARMESH",19,"GUJARAT",92),
("CHANDU",20,"JALNA",88),
("AKSHAY",25,"PUNE",78),
("DHIRAJ",22,"PUNE",60);

SELECT * FROM STUDENTS;

CREATE TABLE DEPARTMENT(
	DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPT_NAME VARCHAR(30) NOT NULL,
    DEPT_HOD VARCHAR(30) DEFAULT "DR.MEHTA",
    STU_ID INT 
    );
    
INSERT INTO DEPARTMENT(DEPT_NAME,STU_ID) VALUES 
("AI&ML",2),
("CSE",4),
("DSA",1),
("DS",5);

ALTER TABLE DEPARTMENT 
ADD CONSTRAINT FOREIGN KEY(STU_ID) REFERENCES STUDENTS(STU_ID);

SELECT S.STU_NAME,S.STU_MARKS ,
D.DEPT_NAME 
FROM DEPARTMENT D 
INNER JOIN STUDENTS S 
ON D.STU_ID=S.STU_ID;

SELECT S.STU_NAME,S.STU_MARKS,
D.DEPT_NAME 
FROM DEPARTMENT D 
NATURAL JOIN STUDENTS S;

SELECT S.STU_NAME,S.STU_MARKS ,
D.DEPT_NAME 
FROM DEPARTMENT D 
LEFT JOIN STUDENTS S 
ON D.STU_ID=S.STU_ID;

SELECT S.STU_NAME,S.STU_MARKS ,
D.DEPT_NAME 
FROM DEPARTMENT D 
RIGHT JOIN STUDENTS S 
ON D.STU_ID=S.STU_ID;

SELECT S.STU_MARKS,D.DEPT_ID
FROM DEPARTMENT D 
CROSS JOIN STUDENTS S;
