CREATE DATABASE STUDENTSDB;
USE STUDENTSDB;

CREATE TABLE STUDENTS(
	STU_ID INT PRIMARY KEY AUTO_INCREMENT,
    STU_NAME VARCHAR(20) NOT NULL,
    STU_AGE INT CHECK(STU_AGE>18),
    STU_MARKS INT NOT NULL
    );
    
ALTER TABLE STUDENTS 
ADD COLUMN STU_ADDRESS VARCHAR(20);

INSERT INTO STUDENTS(STU_NAME,STU_AGE,STU_ADDRESS,STU_MARKS) VALUES
("OM",22,"MUMBAI",90),
("DHARMESH",19,"GUJARAT",92),
("CHANDU",20,"JALNA",88),
("AKSHAY",25,"PUNE",78),
("DHIRAJ",22,"PUNE",60);

SELECT * FROM STUDENTS;

/*MATH FUNCTIONS*/

SELECT ABS(STU_MARKS) FROM STUDENTS;

SELECT FLOOR(100.8);

SELECT CEIL(100.1);

SELECT MOD(2,4);

SELECT POWER(2,2);
SELECT SQRT(2);

SELECT ROUND(200.4444,2);

/*AGGREGATE FUNCTIONS */

SELECT AVG(STU_MARKS) FROM STUDENTS;

SELECT MAX(STU_MARKS) FROM STUDENTS;

SELECT MIN(STU_MARKS) FROM STUDENTS;

SELECT SUM(STU_MARKS) FROM STUDENTS;

SELECT COUNT(STU_MARKS) FROM STUDENTS;

/*cONVERSION FUNCTION*/

SELECT CAST(100 AS CHAR);

SELECT CAST('45' AS SIGNED);

SELECT CONVERT('11-11-2011',DATE);

/*DATE FUNCTIONS*/

SELECT NOW();

SELECT CURDATE();

SELECT CURTIME();

SELECT DAY(NOW());

SELECT MONTH(NOW());
SELECT YEAR(NOW());

