CREATE DATABASE STUDENTSDB;
USE STUDENTSDB;

CREATE TABLE STUDENTS(
	STU_ID INT PRIMARY KEY AUTO_INCREMENT,
    STU_NAME VARCHAR(20) NOT NULL,
    STU_AGE INT CHECK(STU_AGE>18),
    STU_MARKS INT NOT NULL
    );
    
ALTER TABLE STUDENTS 
ADD COLUMN STU_ADDRESS VARCHAR(20);

INSERT INTO STUDENTS(STU_NAME,STU_AGE,STU_ADDRESS,STU_MARKS) VALUES
("OM",22,"MUMBAI",90),
("DHARMESH",19,"GUJARAT",92),
("CHANDU",20,"JALNA",88),
("AKSHAY",25,"PUNE",78),
("DHIRAJ",22,"PUNE",60);

SELECT * FROM STUDENTS;

CREATE VIEW MAX_MARKS AS 
SELECT MAX(STU_MARKS) FROM STUDENTS;

SELECT * FROM MAX_MARKS;

SELECT STU_NAME,STU_MARKS FROM STUDENTS 
WHERE STU_MARKS>(SELECT AVG(STU_MARKS) FROM STUDENTS);

SELECT STU_NAME,STU_MARKS FROM STUDENTS 
WHERE STU_MARKS=(SELECT MAX(STU_MARKS) FROM STUDENTS);